apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rbac.yaml
  - deployment.yaml
  - service.yaml
  - alertmanager-deployment.yaml
  - webhook-logger.yaml

configMapGenerator:
  - name: prometheus-config
    files:
      - prometheus.yml
      - alerts.yml
  - name: alertmanager-config
    files:
      - alertmanager.yml