apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

configMapGenerator:
  - name: notely-config
    literals:
      - APP_VERSION=prod

secretGenerator:
  - name: notely-db
    envs:
      - notely-db.env

images:
  - name: notely
    newName: ghcr.io/burhandevopsnew/notely-platform
    newTag: sha-f8dc07d739c0c704ec1a386c4487e82cda8d2ddb

replicas:
  - name: notely
    count: 3