apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ../../policies
  - ../../stats

configMapGenerator:
  - name: notely-config
    literals:
      - APP_VERSION=prod

secretGenerator:
  - name: notely-db
    envs:
      - notely-db.env

images:
  - name: notely
    newName: ghcr.io/burhandevopsnew/notely-platform
    newTag: sha-1320817cd5a3bdd7ed102d352fbd51248c991115
  - name: notely-stats
    newName: ghcr.io/burhandevopsnew/notely-platform-stats
    newTag: sha-1320817cd5a3bdd7ed102d352fbd51248c991115
