apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

configMapGenerator:
  - name: notely-config
    literals:
      - APP_VERSION=local-kustomize-2

images:
  - name: notely
    newTag: dev

replicas:
  - name: notely
    count: 2