apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ../../postgres
  - ../../monitoring
  - ../../stats

configMapGenerator:
  - name: notely-config
    literals:
      - APP_VERSION=gitops

generators:
  - secret-generator.yaml

images:
  - name: notely
    newName: ghcr.io/burhandevopsnew/notely-platform
    newTag: sha-5247161d3cf1a1b22e647baa011d6acd391171c0
  - name: notely-stats
    newName: ghcr.io/burhandevopsnew/notely-platform-stats
    newTag: sha-5247161d3cf1a1b22e647baa011d6acd391171c0

replicas:
  - name: notely
    count: 2