apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ../../policies
  - ../../postgres
  - ../../monitoring
  - ../../stats
  - ../../logging

configMapGenerator:
  - name: notely-config
    literals:
      - APP_VERSION=gitops

generators:
  - secret-generator.yaml

images:
  - name: notely
    newName: ghcr.io/burhandevopsnew/notely-platform
    newTag: sha-1320817cd5a3bdd7ed102d352fbd51248c991115
  - name: notely-stats
    newName: ghcr.io/burhandevopsnew/notely-platform-stats
    newTag: sha-1320817cd5a3bdd7ed102d352fbd51248c991115
