apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ../../postgres
  - ../../monitoring
  - ../../stats

configMapGenerator:
  - name: notely-config
    literals:
      - APP_VERSION=gitops

generators:
  - secret-generator.yaml

images:
  - name: notely
    newName: ghcr.io/burhandevopsnew/notely-platform
    newTag: sha-fecac15f702b1fe7a9624dc28cf8267a817ba310
  - name: notely-stats
    newName: ghcr.io/burhandevopsnew/notely-platform-stats
    newTag: sha-fecac15f702b1fe7a9624dc28cf8267a817ba310

replicas:
  - name: notely
    count: 2