apiVersion: v1
kind: Secret
metadata:
    name: notely-db
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:rXtwqPvtvU8xdPPQYfwj0LfH2jC894F6KtkOpecQOKzfZDmzHR3ULiydFCbB8J7lMZV162X1TAKz0qIxdnF9Kkm9Gwu8,iv:0voVOkQKQAd7VLaJsf4xsdW0F7IpwVXkQpb1OsFgsYI=,tag:sAlBxsrgrqvsiazO8WYQ9g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBTjBJNWQrZGd0OFFndTlK
            c3pOdTdIS1lLWXQwblNKV043b3hRRFRZV1NFCmo3RlluendOSnN3cnVQZGswNDk5
            dmR5TlgvcXRVRTU5enU2a1h2WW9qWFEKLS0tIDkzUG1tZVNmTitkM0ExOWw0Y2VT
            YUYzNWVUSzhQZWpoOUY0SUNhdGZMdFkK+LZLtEMKDSqDjpUokHAMteztjNSQLluo
            aTWZx5AcZPnQmGXdX7d0vBiCriYxFei4sviWRLjFIkQUqdr2H5fdjw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dgyn3u9la08nmgram3327wetqspnwwk4xsrk5kdywecs9jjlzujsf9hrp7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T13:44:49Z"
    mac: ENC[AES256_GCM,data:o9Wu/4I74Be6u5HNX/x/ZBwjhCnkGG3LHfQE4qXQwoEk+uESN99wV7bfMPI+07Xiu6UWeMKsGdxuiAgDmZl5nr1S1t8h9rA3wm1PVL6ZJXchwagMMRoRplbeG1YRcnhqCKwkLma2nIU2MtBwQBd6Zf8Y3R79/zbmmNOMbib0ITY=,iv:wsCyUiKpDMAD0MyzWLOEjgezAO3ujteXlnpLrHearA8=,tag:HscNnpKT+8WCykOIxFWd2A==,type:str]
    version: 3.13.3
