apiVersion: v1
kind: Secret
metadata:
    name: postgres-credentials
type: Opaque
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:osWQBn6J,iv:QpfnATc7rUcZsYlu/rFI7hgpVGz8JOpcXZPdNFV1PKI=,tag:Z5H3NKLY8sDBDJfjofBcLA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:tjYjfKsX,iv:yvKuIm/rcP7pn3OQaSie7VNmYvstW/kqGLsx07/5vyo=,tag:PCS/BvHL6HPU4A0tz550XQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:QpBGUy7uRibKnp2H7zYAHR68eUU=,iv:WQrle/DtN+v2qMDA+KD3v1nU+dw19n8a6tWoHO3dVdQ=,tag:dXGkKnJ7mbyDM8T4dc646w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaTDNTSjFKK2xMcTNmMzNm
            MVp6WnRvZDFVK0JreEQzRTlIcGQ4UkZnQlZJCkFDVE92VVhNaHhOcDQ2MU1TNG8w
            cUF3VENhV25zYjRrVHV1UUxjTlNhMjQKLS0tIDlJZkZ0Sk5PUGNKVUZzUm9DUWxO
            WnFIc3VYYzVNcG1ISzNRSTNGUHl0Y1kKud8vheJXwjPn0xQb2QOWhpUTgxgnVcmU
            hXG6tbJuSd0wRRtM1POAG/WxpJDQ0e28s/7r+dpWAAu+8DqWE+qe0A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dgyn3u9la08nmgram3327wetqspnwwk4xsrk5kdywecs9jjlzujsf9hrp7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T07:13:21Z"
    mac: ENC[AES256_GCM,data:Gh1NNxTk8l9yHYF+bCH+fufsu2z3GAdiGVejdwIpCJZZwPziVgivaigW1diEBmvML7znPOPBad20qoCvKqW8kSuR8unDzz7YQYsKoWcevxYA/u1sttVqL0MtZdOREG/nTmn2YmsArcE3318l6S9fsTHoBeP61YBlk6myyumE8cc=,iv:3exb8L78QjTDZJkwxrK58F8SZ8MlVVeT9RDmq09hmcs=,tag:BvKE88KXwoEHvrY4K02kbQ==,type:str]
    version: 3.13.3
