apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: notely-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - notely-db.enc.yaml
  - postgres-credentials.enc.yaml