apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: notely
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /stats
            pathType: Prefix
            backend:
              service:
                name: notely-stats
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: notely
                port:
                  number: 80